### ISSUE TITLE
Could you please add Espresso theme too?

### ISSUE THREAD

**Issue by ywpkwon** [adi1090x/kitty-cat#1]
I've been using Espresso theme: https://github.com/dexpota/kitty-themes#espresso. Could you please add?

**Comment by adi1090x** [comment]
clone the repo again and use *import* feature to set the **Espresso** theme. choose URL option in import and paste [this](https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/Espresso.conf) url.
